"updates":
- "directories":
  - "/"
  "groups":
    "cargo":
      "patterns":
      - "*"
  "open-pull-requests-limit": 10
  "package-ecosystem": "cargo"
  "schedule":
    "interval": "daily"
    "time": "04:00"
- "directories":
  - "/"
  "groups":
    "github-actions":
      "patterns":
      - "*"
  "open-pull-requests-limit": 10
  "package-ecosystem": "github-actions"
  "schedule":
    "interval": "daily"
    "time": "04:00"
"version": 2
