name: "nix-update"
on:
  workflow_dispatch:
  schedule:
    - cron: "32 19 * * 0"

jobs:
  flake_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: github.com/boinkor-net/ci-baseline-nix/actions/flake_update@latest
        with:
          app_id: ${{ vars.PR_FIXUP_APP_ID }}
          app_installation_id: ${{ vars.PR_FIXUP_INSTALLATION_ID }}
          app_private_key: ${{ secrets.PR_FIXUP_APP_PRIVATE_KEY }}
