name: "deploy-flake tests"
on:
  workflow_call:

jobs:
  flake_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v26
      - run: nix build --no-link path:.#deploy-flake

  flake_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v26
      - run: nix flake check path:.
